bases:
  - vendor/bigbang/base

configMapGenerator:
  - name: common
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml

patchesStrategicMerge:
  - |-
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    metadata:
      name: bigbang
      namespace: bigbang
    spec:
      url: http://stuart-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__bigbang.git
      secretRef:
        name: zarf-git-secret
