persistence:
  storageClass: "###ZARF_STORAGE_CLASS###"
imagePullSecrets:
  - name: "zarf-registry"
gitea:
  admin:
    username: "zarf-git-user"
    password: "###ZARF_GIT_AUTH_PUSH###"
    email: "zarf@localhost"
  cache:
    builtIn:
      enabled: false
  config:
    APP_NAME: "Zarf Gitops Service"
    server:
      DISABLE_SSH: true
      OFFLINE_MODE: true
    database:
      DB_TYPE: sqlite3
      # Note that the init script checks to see if the IP & port of the database service is accessible, so make sure you set those to something that resolves as successful (since sqlite uses files on disk setting the port & ip won't affect the running of gitea).
      HOST: docker-registry.zarf.svc.cluster.local:5000
    security:
      INSTALL_LOCK: true
    service:
      DISABLE_REGISTRATION: true
    repository:
      ENABLE_PUSH_CREATE_USER: true
      FORCE_PRIVATE: true
  database:
    builtIn:
      postgresql:
        enabled: false
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "2Gi"
