persistence:
  enabled: true
  storageClass: "###ZARF_STORAGE_CLASS###"
image:
  repository: "###ZARF_REGISTRY###/library/registry"
imagePullSecrets:
  - name: zarf-registry
secrets:
  htpasswd: "###ZARF_HTPASSWD###"
# https://github.com/containerd/containerd/blob/v1.5.8/pkg/cri/server/image_pull.go#L412
# thx containerd *magic* :-D
# tlsSecretName: tls-pem
service:
  type: NodePort
  nodePort: "###ZARF_REGISTRY_NODEPORT###"
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "2Gi"
