apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: postgres-operator
data:
  AWS_ENDPOINT: http://minio.minio-operator.svc.cluster.local
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  BACKUP_NUM_TO_RETAIN: "3"
  BACKUP_SCHEDULE: "*/2 * * * *"
  USE_WALG_BACKUP: "true"
  WALG_DISABLE_S3_SSE: "true"
  USE_WALG_RESTORE: "false"
  AWS_S3_FORCE_PATH_STYLE: "true"
